<?php
	const ERRCODE_SUCCESS = 0;
	const ERRCODE_INVALID_PARAM = -1001;
	const ERRCODE_OPERATE_MYSQL	= -1002;
	const ERRCODE_NOT_ENOUGH_MONEY = -1003;
	const ERRCODE_REDIS			= -1004;
	const ERRCODE_USER_EXIST	= -1005;
?>