items = [
	{
		item_id:2,
		name:"红包",
		img:"http://o95rd8icu.bkt.clouddn.com/红包.png",
		type:"a",
		price:-1,
		repeatable:false,
		descript:"红包",
		dir:'v',
		status:1
	},
	{
		item_id:3,
		name:"掌声",
		img:"http://o95rd8icu.bkt.clouddn.com/掌声.png",
		type:"a",
		price:1,
		repeatable:true,
		descript:"掌声",
		dir:'v',
		status:1
	},
	{
		item_id:4,
		name:"我喜欢你",
		img:"http://o95rd8icu.bkt.clouddn.com/我喜欢你.png",
		gif:"http://o95rd8icu.bkt.clouddn.com/心动.gif",
		type:"a",
		price:2,
		repeatable:true,
		descript:"我喜欢你",
		dir:'v',
		status:1
	},
	{
		item_id:5,
		name:"再来一首",
		img:"http://o95rd8icu.bkt.clouddn.com/再来一首.png",
		type:"a",
		price:10,
		repeatable:false,
		descript:"再来一首",
		dir:'v',
		status:1
	},
	{
		item_id:6,
		name:"吻",
		repeatable:false,
		img:"http://o95rd8icu.bkt.clouddn.com/吻.png",
		type:"a",
		price:20,
		descript:"吻",
		dir:'v',
		status:1
	},
	{
		item_id:7,
		name:"玫瑰花",
		img:"http://o95rd8icu.bkt.clouddn.com/玫瑰花.png",
		type:"a",
		price:25,
		repeatable:false,
		descript:"玫瑰花",
		dir:'v',
		status:1
	},
	{
		item_id:8,
		name:"星中歌喉",
		img:"http://o95rd8icu.bkt.clouddn.com/星中歌喉.png",
		gif: "http://o95rd8icu.bkt.clouddn.com/话筒1.gif",
		type:"a",
		price:50,
		repeatable:false,
		descript:"星中歌喉",
		dir:'v',
		status:1
	},
	{
		item_id:9,
		name:"法拉力",
		img:"http://o95rd8icu.bkt.clouddn.com/法拉力.png",
		type:"a",
		price:88,
		repeatable:false,
		descript:"法拉力",
		dir:'h',
		status:1
	},
	{
		item_id:10,
		name:"礼券",
		img:"http://o95rd8icu.bkt.clouddn.com/礼券.png",
		type:"g",
		price:-1,
		repeatable:false,
		descript:"礼券",
		dir:'v',
		status:1
	},
	{
		item_id:11,
		name:"鲜花",
		img:"http://o95rd8icu.bkt.clouddn.com/鲜花.png",
		type:"g",
		price:15,
		repeatable:false,
		descript:"鲜花",
		dir:'v',
		status:1
	},
	{
		item_id:12,
		name:"啤酒套餐",
		img:"http://o95rd8icu.bkt.clouddn.com/啤酒套餐.png",
		type:"g",
		price:30,
		repeatable:false,
		descript:"啤酒套餐",
		dir:'v',
		status:1
	},
	{
		item_id:13,
		name:"洋酒套餐",
		img:"http://o95rd8icu.bkt.clouddn.com/洋酒套餐.png",
		type:"g",
		price:50,
		repeatable:false,
		descript:"洋酒套餐",
		dir:'v',
		status:1
	},
	{
		item_id:14,
		name:"至尊洋酒",
		img:"http://o95rd8icu.bkt.clouddn.com/至尊洋酒.png",
		type:"g",
		price:88,
		repeatable:false,
		descript:"至尊洋酒",
		dir:'v',
		status:1
	}
];